name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  wheel:
    name: Build Wheel
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            manylinux: auto
            target: x86_64-unknown-linux-gnu
            args: --out dist --zig
            interpreter: 3.10 3.14t pypy3.11 graalpy3.11 graalpy3.12
          - os: ubuntu-24.04-arm
            manylinux: auto
            target: aarch64-unknown-linux-gnu
            args: --out dist --zig
            interpreter: 3.10 3.14t pypy3.11 graalpy3.11 graalpy3.12
          - os: ubuntu-latest
            manylinux: auto
            target: riscv64gc-unknown-linux-gnu
            args: --out dist
            interpreter: 3.10 3.14t
          - os: ubuntu-latest
            manylinux: musllinux_1_2
            target: x86_64-unknown-linux-musl
            args: --out dist
            interpreter: 3.10 3.14t
          - os: ubuntu-24.04-arm
            manylinux: musllinux_1_2
            target: aarch64-unknown-linux-musl
            args: --out dist
            interpreter: 3.10 3.14t
          - os: ubuntu-latest
            manylinux: musllinux_1_2
            target: riscv64gc-unknown-linux-musl
            args: --out dist --zig
            interpreter: 3.10 3.14t
          - os: macos-latest
            manylinux: auto
            target: x86_64-apple-darwin
            args: --out dist
            interpreter: 3.10 3.14t
          - os: macos-latest
            manylinux: auto
            target: aarch64-apple-darwin
            args: --out dist
            interpreter: 3.10 3.14t pypy3.11 graalpy3.11 graalpy3.12
          - os: windows-latest
            manylinux: auto
            target: x86_64-pc-windows-msvc
            args: --out dist
            interpreter: 3.10 3.14t pypy3.11
          - os: windows-11-arm
            manylinux: auto
            target: aarch64-pc-windows-msvc
            args: --out dist
            interpreter: 3.10 3.14t

    defaults:
      run:
        shell: nu {0}

    steps:
      - uses: hustcer/setup-nu@v3
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          manylinux: ${{ matrix.manylinux }}
          target: ${{ matrix.target }}
          args: ${{ matrix.args }} --interpreter ${{ matrix.interpreter }}

      - run: ls dist

      - uses: actions/upload-artifact@v6
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.target }}-${{ strategy.job-index }}
          path: ./dist/*.whl
          if-no-files-found: error

  sdist:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nu {0}
    steps:
      - uses: hustcer/setup-nu@v3
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: astral-sh/setup-uv@v7

      - name: Build sdist
        run: uv build --sdist

      - run: ls dist

      - uses: actions/upload-artifact@v6
        with:
          name: sdist
          path: ./dist/*.tar.gz
          if-no-files-found: error

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [wheel, sdist]
    environment: publish
    permissions:
      id-token: write
      attestations: write

    steps:
      - uses: actions/download-artifact@v7
        with:
          path: dist
          merge-multiple: true

      - run: ls dist

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: "dist/*"

      - name: Publish to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: pypa/gh-action-pypi-publish@release/v1
